### ISSUE TITLE
Manage Forum view issue.

### ISSUE THREAD

**Issue by entropylaw** [ppfeufer/aa-forum#1]
Assigned **manage_forum** to a group.
Persons in said group cannot see the Admin view
nor see the Lock, Pin and Delete icons for posts.

**Comment by ppfeufer** [comment]
Hey there,

Just tested this with a test char. I can see what the permission is supposed to see.

> nor see the Lock, Pin and Delete icons for posts.

There are no such icons on posts, they are on topics in the board view.

That's what I see with my test character, who is NOT in any administrative group, just has the `manage_forum` permission through his test group
![image](https://user-images.githubusercontent.com/2989985/121790072-f09c8d00-cbdb-11eb-8a58-43d148ad00ef.png)

**Comment by entropylaw** [comment]
Disregard.... He was looking at the Alliance's AA Instance instead of the Corp instants of AA...
