### ISSUE TITLE
[Feature Request] Spoilers

### ISSUE THREAD

**Issue by Rhaven1** [ppfeufer/aa-forum#118]
it would be useful to condense say discussing a  fitting where can have the fitting in a spoiler so it is folded up in the thread and not  taking up a better part of the page.  

Just to be able to select a section of text and  hide it with a spoiler tag, then  it will expand out if you click on it.

**Comment by ppfeufer** [comment]
That would be a plugin for the CKEditor we use. So you have to find it and install it manually.

https://ckeditor.com/cke4/addons/plugins/all

https://ckeditor.com/cke4/addon/pre

- Download it
- Unzip
- Upload to `myauth/myauth/static/my_static/aa_forum/ckeditor/plugins/`

In your `local.py` add the following below the config for AA Forum

```python
CKEDITOR_CONFIGS["aa_forum"]["external_plugin_resources"] = [
    (
        "pre",
        "/static/my_static/aa_forum/ckeditor/plugins/pre/",
        "plugin.js",
    )
] + CKEDITOR_CONFIGS["aa_forum"]["external_plugin_resources"] 
```

To the list of `extraPlugins` you add the following three lines (you'll find it a bit above in the big config dict):

```python
"dialog",
"widget",
"pre",
```

And 'Pre` (uppercase P) to this dict
```python
{
    "name": "insert",
    "items": [
        "Image",
        "Youtube",
        "Table",
        "HorizontalRule",
        "Smiley",
        "SpecialChar",
        # "PageBreak",
        # "Iframe",
    ],
},
```

Now run static collection and restart supervisor.

This should theoretically work. Keep in mind, that not every plugin is maintained and compatible with the version of CKEditor we use. I couldn't get this one to show up in a quick local test.

Good luck
