### ISSUE TITLE
Localization of forum time

### ISSUE THREAD

**Issue by heguyChen** [ppfeufer/aa-forum#125]
Hello developer, I want to know how to localize the forum time. Is there any place to change its default use of Greenwich Mean Time? If not, can you consider linking with another plug-in of the platform, timezone?

**Comment by ppfeufer** [comment]
Hey there,

The forum uses Eve time (UTC), which is the assumed default in Alliance Auth for displaying time.

**Comment by ppfeufer** [comment]
![New Feature: Support for aa-timezones]

[New Feature: Support for aa-timezones]: https://user-images.githubusercontent.com/2989985/195106607-8caf39c1-7343-404b-a926-e3253558b1ce.png "New Feature: Support for aa-timezones"
