### ISSUE TITLE
[Feature Request] allow audio files to be uploaded too

### ISSUE THREAD

**Issue by resixh** [ppfeufer/aa-forum#134]
### Forum audio upload

In which context would you expect your suggested feature to be useful?

Recoprds of firesides or state of the corps 

### Describe the feature you have in mind

listen in the post
### Additional context

Add any other context or screenshots/mockups about the feature request here.

**Comment by ppfeufer** [comment]
That is out of my hand, I'm not in control of what and what not the editor can do.
