### ISSUE TITLE
[CKEditor] Users can't upload images

### ISSUE THREAD

**Issue by ppfeufer** [ppfeufer/aa-forum#219]
Currently, non-administrative users can't upload images.

This is an upstream bug » https://github.com/hvlads/django-ckeditor-5/issues/197

Leaving this here as a reminder for me.

**Comment by richmcd** [comment]
This appears to be fixed in hvlads/django-ckeditor-5#235, but as of 10/2/2024 no official release includes this pull request.  It is merged into the master branch though.

**Comment by ppfeufer** [comment]
Fixed in v2.8.1 » https://github.com/ppfeufer/aa-forum/releases/tag/v2.8.1
