### ISSUE TITLE
Discord Webhooks

### ISSUE THREAD

**Issue by CokkocZateki** [ppfeufer/aa-forum#43]
Would be great to have a feature where we can add Discord Webhooks. would work great for when adding announcements and it sends it to Discord

Not sure if this would be technically possible but a dank feature nonetheless

**Comment by CokkocZateki** [comment]
Hi ppfeufer

Im not very good at explaining in English but here goes. 

I understand that there are many technical challenges to implement something like this.

From what iv seen on some php projects. A thread of board id could be used as a solution. So whenever something is posted within a given thread it will send it via webhook to discord. I know that replying to the same thread could result in it initiating another webhook ping. 

If it was able to implement perhaps have a condition which could be done with a thread/board id is specified and if the thread/board was updated or a new forum post is added to the board. Perhaps the image below would be alot clearer

![image](https://user-images.githubusercontent.com/16074209/131254390-1eb999f3-03e5-4e02-9ec9-6975c601a2c0.png)

**Comment by ppfeufer** [comment]
A simple solution I am currently playing with, let me know if that's what you're looking for.


![438770b9](https://user-images.githubusercontent.com/2989985/132858907-10b301d5-b88b-4d8a-9329-674187dec1b4.jpg)

![08097a67](https://user-images.githubusercontent.com/2989985/132858821-5340fa52-7abe-4b0d-a480-068e019e6fff.jpg)

This will just post a notification to the channel the webhook is assigned to, every time a new topic is created in this board. It will NOT announce replies to topics, I don't want to build something that potentially spams Discord.

**Comment by CokkocZateki** [comment]
Looks great. Does it also post anything on a forum post update?

**Comment by ppfeufer** [comment]
No, only when a new topic is created. Everything else I consider as spam.

**Comment by ppfeufer** [comment]
Released with v1.1.0
